- name: Install packages
  apt:
    name:
      - gcc
      - clang
      - make
      - automake
      - autoconf
      - libpcre3-dev
    state: present

- name: Git Clone
  git:
    repo: 'https://github.com/jbboehr/php-psr.git'
    dest: /home/ubuntu/php-psr
    clone: yes
    update: yes

- name: Go to the directory 
  command: "{{ item }}" 
  args:
    chdir: php-psr/
      #- name: Execute commands
      #shell:
  loop:
    - "phpize"
    - "./configure"
    - "make"
      #- "make test"
    - "sudo make install"

- name: Copy phalcon.ini
  template:
    src: phalcon.j2
    dest: "{{ phalcon_path }}/50-phalcon.ini"
    follow: yes

  notify:
    #- Reload systemd
    - Restart nginx
    - Restart php-fpm
