---
# tasks file for server.web
- include_tasks:
    file: prerrequisitos.yml

- include_tasks:
    file: install_nginx_php.yml

- include_tasks:
    file: install_psr.yml

- include_tasks:
    file: install_phalcon.yml
